<?php
declare(strict_types=1);

namespace Another\Plugin\Another_Wishlist\Tests\Unit\Models;

use Another\Plugin\Another_Wishlist\Models\Wishlist_Model;
use Another\Plugin\Another_Wishlist\Tests\Unit\TestCase;
use Brain\Monkey\Functions;

class Wishlist_Test extends TestCase
{
	public function set_up(): void
	{
		parent::set_up(); // TODO: Change the autogenerated stub
		Functions\when('wp_generate_uuid4')->justReturn('4d59e1ac-0e1b-4d20-94b6-2dbfa8159850');
	}

	/**
	 * @return void
	 *
	 * @covers \Another\Plugin\Another_Wishlist\Models\Wishlist_Model::__construct()
	 * @covers \Another\Plugin\Another_Wishlist\Models\Wishlist_Model::user_id()
	 * @covers \Another\Plugin\Another_Wishlist\Models\Wishlist_Model::set_user_id()
	 */
	public function test_user_id()
	{
		$wishlist = new Wishlist_Model(['user_id' => 1]);
		$this->assertEquals(1, $wishlist->user_id());
	}

	/**
	 * @return void
	 *
	 * @covers \Another\Plugin\Another_Wishlist\Models\Wishlist_Model::__construct()
	 * @covers \Another\Plugin\Another_Wishlist\Models\Wishlist_Model::id()
	 * @covers \Another\Plugin\Another_Wishlist\Models\Wishlist_Model::set_id()
	 */
	public function test_id()
	{
		$wishlist = new Wishlist_Model(['id' => 1]);
		$this->assertEquals(1, $wishlist->id());
	}

	/**
	 * @return void
	 *
	 * @covers \Another\Plugin\Another_Wishlist\Models\Wishlist_Model::__construct()
	 * @covers \Another\Plugin\Another_Wishlist\Models\Wishlist_Model::guid()
	 * @covers \Another\Plugin\Another_Wishlist\Models\Wishlist_Model::set_guid()
	 */
	public function test_guid()
	{
		$wishlist = new Wishlist_Model(['guid' => '123']);
		$this->assertEquals('123', $wishlist->guid());
	}

	/**
	 * @return void
	 *
	 * @covers \Another\Plugin\Another_Wishlist\Models\Wishlist_Model::__construct()
	 * @covers \Another\Plugin\Another_Wishlist\Models\Wishlist_Model::title()
	 * @covers \Another\Plugin\Another_Wishlist\Models\Wishlist_Model::set_title()
	 */
	public function test_title()
	{
		$wishlist = new Wishlist_Model(['title' => 'test']);
		$this->assertEquals('test', $wishlist->title());
	}

	/**
	 * @return void
	 *
	 * @covers \Another\Plugin\Another_Wishlist\Models\Wishlist_Model::__construct()
	 * @covers \Another\Plugin\Another_Wishlist\Models\Wishlist_Model::description()
	 * @covers \Another\Plugin\Another_Wishlist\Models\Wishlist_Model::set_description()
	 */
	public function test_description()
	{
		$wishlist = new Wishlist_Model(['description' => 'test']);
		$this->assertEquals('test', $wishlist->description());
	}

	/**
	 * @return void
	 *
	 * @covers \Another\Plugin\Another_Wishlist\Models\Wishlist_Model::__construct()
	 * @covers \Another\Plugin\Another_Wishlist\Models\Wishlist_Model::object_ids()
	 * @covers \Another\Plugin\Another_Wishlist\Models\Wishlist_Model::set_object_ids()
	 */
	public function test_object_ids()
	{
		$wishlist = new Wishlist_Model(['object_ids' => [1, 2, 3]]);
		$this->assertEquals([1, 2, 3], $wishlist->object_ids());
	}

	/**
	 * @return void
	 *
	 * @covers \Another\Plugin\Another_Wishlist\Models\Wishlist_Model::__construct()
	 * @covers \Another\Plugin\Another_Wishlist\Models\Wishlist_Model::visibility()
	 * @covers \Another\Plugin\Another_Wishlist\Models\Wishlist_Model::set_visibility()
	 */
	public function test_visibility()
	{
		$wishlist = new Wishlist_Model(['visibility' => Wishlist_Model::VISIBILITY_PUBLIC]);
		$this->assertEquals(Wishlist_Model::VISIBILITY_PUBLIC, $wishlist->visibility());
	}

	/**
	 * @return void
	 *
	 * @covers \Another\Plugin\Another_Wishlist\Models\Wishlist_Model::__construct()
	 * @covers \Another\Plugin\Another_Wishlist\Models\Wishlist_Model::user_id()
	 * @covers \Another\Plugin\Another_Wishlist\Models\Wishlist_Model::id()
	 * @covers \Another\Plugin\Another_Wishlist\Models\Wishlist_Model::guid()
	 * @covers \Another\Plugin\Another_Wishlist\Models\Wishlist_Model::title()
	 * @covers \Another\Plugin\Another_Wishlist\Models\Wishlist_Model::description()
	 * @covers \Another\Plugin\Another_Wishlist\Models\Wishlist_Model::object_ids()
	 * @covers \Another\Plugin\Another_Wishlist\Models\Wishlist_Model::visibility()
	 * @covers \Another\Plugin\Another_Wishlist\Models\Wishlist_Model::set_id()
	 * @covers \Another\Plugin\Another_Wishlist\Models\Wishlist_Model::set_user_id()
	 * @covers \Another\Plugin\Another_Wishlist\Models\Wishlist_Model::set_guid()
	 * @covers \Another\Plugin\Another_Wishlist\Models\Wishlist_Model::set_title()
	 * @covers \Another\Plugin\Another_Wishlist\Models\Wishlist_Model::set_description()
	 * @covers \Another\Plugin\Another_Wishlist\Models\Wishlist_Model::set_object_ids()
	 * @covers \Another\Plugin\Another_Wishlist\Models\Wishlist_Model::set_visibility()
	 */
	public function test_multiple_attributes()
	{
		$wishlist = new Wishlist_Model([
			'user_id' => 1,
			'id' => 2,
			'guid' => '123',
			'title' => 'test',
			'description' => 'test',
			'object_ids' => [1, 2, 3],
			'visibility' => Wishlist_Model::VISIBILITY_PUBLIC,
		]);

		$this->assertEquals(1, $wishlist->user_id());
		$this->assertEquals(2, $wishlist->id());
		$this->assertEquals('123', $wishlist->guid());
		$this->assertEquals('test', $wishlist->title());
		$this->assertEquals('test', $wishlist->description());
		$this->assertEquals([1, 2, 3], $wishlist->object_ids());
		$this->assertEquals('public', $wishlist->visibility());
	}
}
