name: Coding Standards

on:
  # Run on all relevant pushes (except to main) and on all relevant pull requests.
  push:
    branches-ignore:
      - 'master'
    paths:
      - '**.php' # Includes config/*.php files.
      - '.phpcs.xml.dist'
      - 'phpcs.xml.dist'
      - '.github/workflows/**'
  pull_request:
    paths:
      - '**.php' # Includes config/*.php files.
      - '.phpcs.xml.dist'
      - 'phpcs.xml.dist'
      - '.github/workflows/**'
  # Allow manually triggering the workflow.
  workflow_dispatch:

# Cancels all previous workflow runs for the same branch that have not yet completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-cs:
    name: 'Check code style'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Determine the base branch for the file diff
        id: base_branch
        env:
          BASE_REF: ${{ github.base_ref }}
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            echo "NAME=$BASE_REF" >> "$GITHUB_OUTPUT"
            echo "REF=origin/$BASE_REF" >> "$GITHUB_OUTPUT"
          else
            echo 'NAME=master' >> "$GITHUB_OUTPUT"
            echo "REF=origin/master" >> "$GITHUB_OUTPUT"
          fi

      - name: Fetch base branch
        run: git fetch --no-tags --depth=1 origin ${{ steps.base_branch.outputs.NAME }}

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 'latest'
          coverage: none
          tools: cs2pr

      # Validate the composer.json file.
      # @link https://getcomposer.org/doc/03-cli.md#validate
      - name: Validate Composer installation
        run: composer validate --no-check-all

      # Install dependencies and handle caching in one go.
      # @link https://github.com/marketplace/actions/install-php-dependencies-with-composer
      - name: Install Composer dependencies
        uses: ramsey/composer-install@v3
        with:
          # Bust the cache at least once a week - output format: YYYY-MM-DD.
          custom-cache-suffix: $(/bin/date -u --date='last Mon' "+%F")

      - name: Check PHP code style for the changes made in the branch only
        id: phpcs
        run: composer phpcs

      - name: Show PHPCS results in PR
        if: ${{ always() && steps.phpcs.outcome == 'failure' }}
        run: cs2pr ./phpcs-report.xml
