name: Finish Coveralls build
on:
  push:
    branches:
      - master
      - "release/**"
      - "hotfix/[0-9]+.[0-9]+*"
      - "feature/**"
    paths:
      # From test.yml
      - '**.php' # Includes config/*.php and lib/*.php files.
      - 'composer.json'
      - 'composer.lock'
      - 'phpunit.xml.dist'
      - 'phpunit-wp.xml.dist'
      - '.github/workflows/unittest.yml'
      - 'tests/**'
  pull_request:
    paths:
      - '**.php' # Includes config/*.php and lib/*.php files.
      - 'composer.json'
      - 'composer.lock'
      - 'phpunit.xml.dist'
      - 'phpunit-wp.xml.dist'
      - '.github/workflows/unittest.yml'
      - 'tests/**'

# Don't run a second workflow for the same PR or commit if one is already running.
concurrency:
  # The concurrency group contains the workflow name and the branch name.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  finish_coveralls_build:
    name: "Finish coveralls build"
    runs-on: ubuntu-latest
    steps:

      # Wait for the PHP and JS tests to start.
      - name: Sleep for 30 seconds
        run: sleep 30s
        shell: bash

      # Wait for the PHP and JS tests to finish.
      # NOTE: The ref value should be different when triggered by pull_request event.
      #       See: https://github.com/lewagon/wait-on-check-action/issues/25.
      - name: "Wait on tests (PR)"
        uses: lewagon/wait-on-check-action@ccfb013c15c8afb7bf2b7c028fb74dc5a068cccc # lewagon/wait-on-check-action@v1.3.4
        if: github.event_name == 'pull_request'
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          check-regexp: Test|TestJS

      - name: "Wait on tests (push)"
        if: github.event_name != 'pull_request'
        uses: lewagon/wait-on-check-action@ccfb013c15c8afb7bf2b7c028fb74dc5a068cccc # lewagon/wait-on-check-action@v1.3.4
        with:
          ref: ${{ github.sha }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          check-regexp: Test|TestJS

      - name: "Coveralls Finished"
        uses: coverallsapp/github-action@v2
        env:
          COVERALLS_SERVICE_NUMBER: ${{ github.sha }} # Connect all builds together.
        with:
          github-token: ${{ secrets.COVERALLS_REPO_TOKEN }}
          carryforward: "unit-php-8.3,package-another-wishlist"
          parallel-finished: true
