name: Test

on:
  # Run on relevant pushes to select branches and on all relevant pull requests.
  push:
    branches:
      - master
      - "release/**"
      - "hotfix/[0-9]+.[0-9]+*"
      - "feature/**"
    paths:
      - '**.php' # Includes config/*.php and lib/*.php files.
      - 'composer.json'
      - 'composer.lock'
      - 'phpunit.xml.dist'
      - 'phpunit-wp.xml.dist'
      - '.github/workflows/test.yml'
      - 'tests/**'
  pull_request:
    paths:
      - '**.php' # Includes config/*.php and lib/*.php files.
      - 'composer.json'
      - 'composer.lock'
      - 'phpunit.xml.dist'
      - 'phpunit-wp.xml.dist'
      - '.github/workflows/test.yml'
      - 'tests/**'
  # Allow manually triggering the workflow.
  workflow_dispatch:

# Cancels all previous workflow runs for the same branch that have not yet completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php_version: ["8.2", "8.3"]
        coverage: [false]

        # Run code coverage only on high/low PHP.
        include:
          - php_version: 8.3
            coverage: true

    name: "Unit Test: PHP ${{ matrix.php_version }}"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Composer dependencies, generate vendor_prefixed directory and run dependency injection
        uses: ramsey/composer-install@v3
        with:
          # Bust the cache at least once a week - output format: YYYY-MM-DD.
          custom-cache-suffix: $(/bin/date -u --date='last Mon' "+%F")

      # Remove packages which are not PHP cross-version compatible and only used for the prefixing.
      # - humbug/php-scoper is only needed to actually do the prefixing, so won't be shipped anyway.
      - name: Delete dev dependencies which are not cross-version compatible
        run: composer remove --dev --no-scripts humbug/php-scoper

      - name: Remove vendor directory
        run: rm -rf vendor/*

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php_version }}
          ini-values: zend.assertions=1, error_reporting=-1, display_errors=On
          coverage: ${{ matrix.coverage == true && 'xdebug' || 'none' }}
        env:
          update: true

      # The PHP platform requirement would prevent updating the test utilities to the appropriate versions.
      # As long as the `composer update` is run selectively to only update the test utils, removing this is fine.
      - name: "Composer: remove the PHP platform requirement"
        run: composer config --unset platform.php

      # Install dependencies and handle caching in one go.
      # - Updates the test utilities (and only those!) to the most appropriate version
      #   for the PHP version on which the tests will be run.
      # @link https://github.com/marketplace/actions/install-php-dependencies-with-composer
      - name: Install Composer dependencies
        uses: ramsey/composer-install@v3
        with:
          # Force a `composer update` run.
          dependency-versions: "highest"
          # But make it selective.
          composer-options: "yoast/wp-test-utils --with-dependencies --no-scripts"
          # Bust the cache at least once a week - output format: YYYY-MM-DD.
          custom-cache-suffix: $(/bin/date -u --date='last Mon' "+%F")

      - name: Run unit tests
        if: ${{ matrix.coverage == false }}
        run: composer test

      - name: Run the unit tests with code coverage
        if: ${{ matrix.coverage == true }}
        run: composer coverage

      - name: Upload coverage results to Coveralls
        if: ${{ success() && matrix.coverage == true }}
        uses: coverallsapp/github-action@v2
        env:
          COVERALLS_SERVICE_NUMBER: ${{ github.sha }} # Connect all builds together.
        with:
          format: clover
          file: build/logs/clover.xml
          flag-name: unit-php-${{ matrix.php_version }}
          parallel: true
